### ISSUE TITLE
[BUG] ORT_INVALID_PROTOBUF - message: Failed to load model because protobuf parsing failed

### ISSUE THREAD

**Issue by amuniz** [langchain4j/langchain4j-embeddings#22] opened 2024-04-05 09:54 UTC
**Describe the bug**
Getting the following error when instantiating `AllMiniLmL6V2EmbeddingModel`:

```
java.lang.ExceptionInInitializerError
	at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModelIT.should_embed(AllMiniLmL6V2EmbeddingModelIT.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_INVALID_PROTOBUF - message: Failed to load model because protobuf parsing failed.
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:42)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:22)
	at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18)
	... 4 more
Caused by: ai.onnxruntime.OrtException: Error code - ORT_INVALID_PROTOBUF - message: Failed to load model because protobuf parsing failed.
	at ai.onnxruntime.OrtSession.createSession(Native Method)
	at ai.onnxruntime.OrtSession.<init>(OrtSession.java:91)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:276)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:249)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:261)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:37)
	... 6 more
```

**To Reproduce**
Reproducible with current tests: `mvn -pl langchain4j-embeddings-all-minilm-l6-v2 test -Dtest=AllMiniLmL6V2EmbeddingModelIT#should_embed`

**Expected behavior**
`AllMiniLmL6V2EmbeddingModel` can be instantiated.

**Please complete the following information:**
- LangChain4j version: tip of main (as of now https://github.com/langchain4j/langchain4j-embeddings/commit/0a86294c72aab3fffd266eaa9ba885f64860f8d2)
- Java version: 17

**Additional context**
This is also reproducible in a separate app which is using `AllMiniLmL6V2EmbeddingModel`.

**Comment by langchain4j** [comment] 2024-04-11 13:31
HI @amuniz could you please check if you have this file in your repo: `.../langchain4j-embeddings-all-minilm-l6-v2/src/main/resources/all-minilm-l6-v2.onnx`?
If not, you will need to install git LFS and do `git lfs pull`.

**Comment by langchain4j** [comment] 2024-04-11 13:35
Closing this as it is not a bug, but misconfiguration. Feel free to reopen if you have further issues.

**Closed by langchain4j** 2024-04-11 13:35 UTC
Labels: bug
